### ISSUE TITLE
Discussion on the merits of using releases vs latest for dependent services in PR builds.

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/ci-deployment#12]
Related to PR #4 

The rancher_pr_deploy.sh script uses images tagged with the GitHub latest release tag for dependent services. For example, nearby-services-api and pharmacy-db are dependant services of connecting-to-services and (at the time of writing) a pull request will use the docker images tagged with 0.4.1 and 0.0.1-beta for the dependent services respectively.

There is some question as to whether the latest *release* images or just the images tagged *latest* should be used.

One of the benefits of using the releases is it gives some amount of stability between subsequent builds of a given PR and it also makes explicit, in the image names, which version of a dependent service is being used. The drawback of using releases is it adds to the complexity of the PR deployment script and requires the use of naming conventions.

We use a naming convention to allow derive the mapping between GitHub and DockerHub repos and also between GitHub repos and Rancher variable names. As it stands the naming convention will still be required even if we change to using latest builds as we parse the docker-compose files to determine the names of the 'parent' service and any dependant services. There are ways around this however.

I'm not against changing to using images tagged latest I just want to make sure it's a considered decision.

Any thoughts?

**Comment by beseven** [comment]
I agree with versioning based on release, however, I think it shouldn't have to be in the deploy scripts as the info can't necessarily be automated. E.g the script wouldn't know that `gp-finder` needs to use the image form `profiles-db` with release `0.1.0` as the release `0.2.0` changes the schema -  Upgrading a service to use a specific image in Rancher is straight forward and our deployments to live are still manual -so a bit of human intervention is still needed in my opinion.

**Comment by adamgraves-choices** [comment]
This can be closed off as we've agreed that using `latest` is OK, and this has now been implemented.
