### ISSUE TITLE
Delete rancher stack when PR is merged

### ISSUE THREAD

**Issue by st3v3nhunt** [nhsuk/ci-deployment#2]
Atm, CI builds create new stacks in rancher. When the PR is deleted the stack isn't - it should be.

This issue is to highlight the fact that when a PR is merged (or closed) the stack on Rancher for that PR should be deleted.

**Comment by adamgraves-choices** [comment]
With the latest changes adding a description to the stack, we now use https://github.com/nhsuk/rancher-cleanup which removes old PRs every 10 minutes.
