### ISSUE TITLE
Code in rancher-pr-deploy still has some profile specific hard coded values

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/ci-deployment#3]
```
echo "profiles_docker_image_tag=pr-${TRAVIS_PULL_REQUEST}"
RANCHER_STACK_NAME="profiles-pr-${TRAVIS_PULL_REQUEST}"
```

Need to parameterise them

**Comment by st3v3nhunt** [comment]
Suggestion: `RANCHER_STACK_NAME="${TRAVIS_REPO_SLUG}-pr-${TRAVIS_PULL_REQUEST}"`

The `<thing>_docker_image_tag` is a bit more involved due to having to match that expected in the rancher config

**Comment by neilbmclaughlin** [comment]
The repo slug will need sanitising ~I think - I don't believe rancher allows~ rancher doesn't allow non alpha-numerics. ~Let me know if you think that isn't the case otherwise I'll test it out.~

**Comment by st3v3nhunt** [comment]
You are correct, it doesn't like it :(

**Comment by st3v3nhunt** [comment]
Scripts are generic now, this is no longer valid. Closing.
