### ISSUE TITLE
Deployment failure will not be notified.

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/ci-deployment#34]
Detection of deployment failure in travis/deploy.sh will fail as a consequence of the usage of `set -e` _and_ the use of $?.

See [here](https://github.com/koalaman/shellcheck/wiki/SC2181) for a description of the problem. 

The problem was flagged by `shellcheck`.

**Comment by adamgraves-choices** [comment]
Closed by https://github.com/nhsuk/ci-deployment/pull/54
