### ISSUE TITLE
Remove duplication of definitions

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/ci-deployment#5]
The code in rancher_pr_travis.sh contains environment variables which are hard coded (e.g. `splunk_hec_token=${SPLUNK_HEC_TOKEN}`) and also in the rancher-compose.yml as defaults. Probably better, from a code duplication perspective, for them to be defined in a single place.

**Comment by st3v3nhunt** [comment]
No longer as issue, closing.
