### ISSUE TITLE
Lint scripts in git hook.

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/ci-deployment#6]
shellcheck seems to do the job and it would probably be in a pre-commit hook.

Need to work out how to get the git hook installed across all dev machines.

**Comment by st3v3nhunt** [comment]
See #47 for the `shellcheck` check run in Travis

**Comment by adamgraves-choices** [comment]
@neilbmclaughlin are you happy for this to be closed off now `shellcheck` is running as part of Travis?

**Comment by neilbmclaughlin** [comment]
Yep, looks good.
