### ISSUE TITLE
Remove hard coded version number in URL for templates

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/ci-deployment#8]
The curl requests for the rancher/docker templates are currently hard coded to version 0.

We should probably be using release tagging and cloning/copying the latest tagged release to avoid having to make a code change when the templates change.

**Comment by neilbmclaughlin** [comment]
Looking at the GitHub API - it is possible to get the URL for the zipball of the latest release of a repo (e.g. `curl -s "https://api.github.com/repos/{repo-slug}/releases/latest"  | jq -r '.zipball_url'`) which could be downloaded, unzipped and used.

**Comment by st3v3nhunt** [comment]
@neilbmclaughlin Am I correct in stating that the version is handled by rancher catalog and the way it requests the latest template version as defined in the `config.yml`? If so, this issue is done? In which case can you confirm and close please?

**Comment by adamgraves-choices** [comment]
@st3v3nhunt This has actually been fixed in an earlier commit. The newest version of the scripts does exactly what you say, and gets the template version from the API. Therefore this can be closed off.
